### ISSUE TITLE
Doesn't work with Float32

### ISSUE THREAD

**Issue by marius311** [Jutho/OptimKit.jl#7]
First, thanks a ton for this package, it really fills in exactly the missing piece for me of other Julia optimization packages that only really work with `Array`. However, at the moment OptimKit seems to only work with `Float64`, e.g. 

```julia
julia> using OptimKit

julia> optimize(x->(x'x,2x), ones(Float32,5), LBFGS())
ERROR: MethodError: no method matching OptimKit.HagerZhangLineSearchIterator(::var"#1#2", ::typeof(OptimKit._retract), ::typeof(OptimKit._inner), ::OptimKit.LineSearchPoint{Float32,Array{Float32,1},Array{Float32,1}}, ::Array{Float32,1}, ::Float64, ::Bool, ::HagerZhangLineSearch{Float64})
```

Would be great if OptimKit could work with any eltype `<:Real` (not just `Float32`, but `BigFloat`, etc...). I unfortunately don't have the time to make a proper PR, but if its helpful, I have it working with Float32 here: https://github.com/marius311/OptimKit.jl/commit/ce2136a47b50a8ef9ffea297db1c58e2ef59c697 where with this you can do 

```julia
optimize(x->(x'x,2x), ones(Float32,5), LBFGS(gradtol=1f-8))
```
 and it works.

**Comment by Jutho** [comment]
Thanks, I definitely want this package to support generic `eltype`s, though I did not test it as such. In fact, this is one of my only packages which lacking proper tests. So thanks for pointing this out and proposing a fix. 

I have a fix, which is slightly different from yours. I will push and tag a new release.

**Comment by Jutho** [comment]
So this should be fixed on master; before I actually tag the new release, you might want to test with your current applications?

**Comment by marius311** [comment]
Just checked and your solution works for me (and is better since you don't have to specify the `gradtol` type). Thanks for the quick fix!
